SETUP: Initial setup
Real-Dev-Squad/tiny-site-frontend pull request #8
Opened 2023-09-07 11:50 UTC by sahsisunny

2023-09-08 06:00 UTC, iamitprakash requested changes
test case stats are missing

2023-09-09 04:17 UTC, sahsisunny commented
> test case stats are missing 

I have already created an issue ticket for adding a test framework since it's currently not included.

2023-09-09 08:47 UTC, iamitprakash commented
@sahsisunny please add working application video or PIC

2023-09-09 12:16 UTC, Pratiyushkumar reviewed
agreed with @iamitprakash, you should add video of working application

2023-09-10 10:40 UTC, Pratiyushkumar reviewed
Request you remove unwanted  code from .css files and.tsx files

2023-09-10 10:40 UTC, Pratiyushkumar commented on public/vercel.svg
remove this svg if not needed

2023-09-10 10:40 UTC, Pratiyushkumar commented on public/next.svg
remove this svg if not required

2023-09-10 10:40 UTC, Pratiyushkumar commented on src/app/favicon.ico
also this favicon

2023-09-10 10:40 UTC, Pratiyushkumar commented on src/app/page.tsx
we could have removed these unwanted code.

2023-09-12 06:55 UTC, sahsisunny commented
@Pratiyushkumar default templates will be removed when we make other components and pages.

2023-09-15 08:03 UTC, vinit717 approved these changes

2023-09-15 08:16 UTC, Pratiyushkumar approved these changes

2023-09-15 13:59 UTC, merged